// {{ComponentName}}.tsx
// Generated by Atlas (Design System Builder)
// Atomic level: {{atomic_level}}
// Zero hardcoded values - all styling from tokens

import React from 'react';
import styles from './{{ComponentName}}.module.css';

/**
 * {{ComponentDescription}}
 *
 * @example
 * ```tsx
 * <{{ComponentName}} variant="primary" size="md">
 *   {{ExampleContent}}
 * </{{ComponentName}}>
 * ```
 */

export interface {{ComponentName}}Props {
  /** Visual style variant */
  variant?: {{VariantType}};

  /** Size variant */
  size?: {{SizeType}};

  /** Content */
  children: React.ReactNode;

  /** Click handler */
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;

  /** Disabled state */
  disabled?: boolean;

  /** Additional CSS classes */
  className?: string;

  /** HTML id attribute */
  id?: string;

  /** ARIA label for accessibility */
  'aria-label'?: string;

  {{AdditionalProps}}
}

/**
 * {{ComponentName}} component
 *
 * Built with:
 * - TypeScript strict mode
 * - WCAG AA accessibility
 * - Token-based styling (zero hardcoded values)
 * - Full test coverage
 */
export const {{ComponentName}}: React.FC<{{ComponentName}}Props> = ({
  variant = '{{DefaultVariant}}',
  size = '{{DefaultSize}}',
  children,
  onClick,
  disabled = false,
  className = '',
  id,
  'aria-label': ariaLabel,
  {{AdditionalPropDestructure}}
}) => {
  // Construct CSS classes from props
  const componentClasses = [
    styles.{{componentName}},
    styles[`{{componentName}}-${variant}`],
    styles[`{{componentName}}-${size}`],
    disabled && styles[`{{componentName}}-disabled`],
    className,
  ]
    .filter(Boolean)
    .join(' ');

  // Event handlers
  const handleClick = (event: React.MouseEvent<HTMLElement>) => {
    if (disabled) {
      event.preventDefault();
      return;
    }
    onClick?.(event);
  };

  return (
    <{{HtmlElement}}
      id={id}
      className={componentClasses}
      onClick={handleClick}
      disabled={disabled}
      aria-disabled={disabled}
      aria-label={ariaLabel}
      {{AdditionalAttributes}}
    >
      {children}
    </{{HtmlElement}}>
  );
};

// Display name for debugging
{{ComponentName}}.displayName = '{{ComponentName}}';

// Default props
{{ComponentName}}.defaultProps = {
  variant: '{{DefaultVariant}}',
  size: '{{DefaultSize}}',
  disabled: false,
};
