-- =========================================================
-- POSTGRESQL COMMENT ON EXAMPLES
-- =========================================================
-- Purpose: Document database objects with embedded comments
-- Benefits: Self-documenting database, visible in IDE/tools
-- Reference: https://www.postgresql.org/docs/current/sql-comment.html
-- =========================================================

-- =========================================================
-- TABLE COMMENTS
-- =========================================================

comment on table users is
  'Stores user accounts. Each user can belong to multiple teams via team_members.';

comment on table posts is
  'User-generated content. Supports soft deletes (deleted_at) for audit trail.';

comment on table team_members is
  'Junction table for many-to-many relationship between users and teams.';

-- =========================================================
-- COLUMN COMMENTS
-- =========================================================

-- Primary keys
comment on column users.id is
  'Primary key. UUID v4 generated by gen_random_uuid().';

-- Foreign keys
comment on column posts.user_id is
  'Foreign key to users.id. CASCADE delete removes user posts on user deletion.';

comment on column posts.team_id is
  'Foreign key to teams.id. Team that owns this post. SET NULL on team deletion.';

-- Timestamps
comment on column users.created_at is
  'Timestamp when user account was created. Defaults to now().';

comment on column users.updated_at is
  'Timestamp when user was last modified. Updated by trigger.';

comment on column posts.deleted_at is
  'Soft delete timestamp. NULL = active, non-NULL = deleted. Use for audit trail.';

-- JSONB fields
comment on column users.metadata is
  'Flexible JSONB field for extensibility. Stores user preferences, settings, etc.';

comment on column posts.tags is
  'Array of tag strings for flexible categorization. Indexed with GIN for performance.';

-- Enums/Constrained fields
comment on column users.status is
  'User account status. CHECK constraint: active, suspended, banned, deleted.';

comment on column posts.visibility is
  'Content visibility. Values: public, private, team, unlisted. Affects RLS policies.';

-- Business logic fields
comment on column posts.published_at is
  'When post was published. NULL = draft. Used in RLS for time-based access control.';

comment on column users.email_verified_at is
  'When email was verified. NULL = unverified. Required for certain features.';

-- =========================================================
-- CONSTRAINT COMMENTS
-- =========================================================

comment on constraint users_email_valid on users is
  'Ensures email format is valid using regex pattern.';

comment on constraint posts_published_has_title on posts is
  'Business rule: Published posts must have non-empty title.';

comment on constraint users_age_adult on users is
  'Legal requirement: All users must be 18+.';

-- =========================================================
-- INDEX COMMENTS
-- =========================================================

comment on index idx_users_email is
  'Unique index on email for fast login lookups. Also enforces email uniqueness.';

comment on index idx_posts_user_created is
  'Composite index for user timeline queries. Optimizes: WHERE user_id = ? ORDER BY created_at DESC.';

comment on index idx_posts_tags_gin is
  'GIN index for array overlap queries. Supports: WHERE tags && ARRAY[''tag1'', ''tag2''].';

comment on index idx_posts_search_gist is
  'Full-text search index using trigrams. Supports: WHERE title ILIKE ''%query%''.';

-- =========================================================
-- VIEW COMMENTS
-- =========================================================

comment on view active_users is
  'Materialized view of users with status = ''active'' and email_verified_at IS NOT NULL. Refreshed hourly.';

comment on view post_stats is
  'Aggregated post statistics by user. Expensive to compute, cached in view.';

-- =========================================================
-- FUNCTION COMMENTS
-- =========================================================

comment on function trigger_set_updated_at() is
  'Trigger function that automatically updates updated_at column to now() on every row update.';

comment on function audit_log_changes() is
  'Audit trigger that logs all INSERT/UPDATE/DELETE operations to audit_log table as JSONB.';

comment on function user_has_permission(uuid, text) is
  'Security definer function. Checks if user has specific permission. Returns boolean.';

-- =========================================================
-- POLICY COMMENTS
-- =========================================================

comment on policy "users_own_data" on users is
  'RLS policy: Users can only read/modify their own user record. Admin role bypasses.';

comment on policy "posts_team_access" on posts is
  'RLS policy: Users can access posts from their teams. Uses optimized JOIN pattern for performance.';

comment on policy "posts_public_read" on posts is
  'RLS policy: Public read access for published posts where visibility = ''public'' and published_at <= now().';

-- =========================================================
-- TRIGGER COMMENTS
-- =========================================================

comment on trigger trg_users_updated_at on users is
  'Before UPDATE trigger that sets updated_at = now(). Uses trigger_set_updated_at() function.';

comment on trigger trg_posts_audit on posts is
  'After INSERT/UPDATE/DELETE trigger that logs changes to audit_log. Uses audit_log_changes() function.';

-- =========================================================
-- SCHEMA COMMENTS
-- =========================================================

comment on schema public is
  'Default public schema. Contains all application tables, views, and functions.';

comment on schema audit is
  'Audit schema. Contains audit_log table and related audit functions. Read-only for app.';

-- =========================================================
-- TYPE COMMENTS (Enums, Composites)
-- =========================================================

comment on type user_status is
  'Enum type for user account status. Values: active, suspended, banned, deleted.';

comment on type content_visibility is
  'Enum type for content visibility. Values: public, private, team, unlisted.';

-- =========================================================
-- DOMAIN COMMENTS
-- =========================================================

comment on domain email is
  'Custom domain type for email validation. Uses regex: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$';

comment on domain url is
  'Custom domain type for URL validation. Uses regex to enforce valid HTTP/HTTPS URLs.';

-- =========================================================
-- BEST PRACTICES FOR COMMENTS
-- =========================================================
-- 1. Explain WHY, not WHAT (code shows what)
-- 2. Document business rules and constraints
-- 3. Explain performance optimizations (indexes)
-- 4. Note security implications (RLS policies)
-- 5. Include examples for complex logic
-- 6. Keep comments up-to-date with schema changes
-- 7. Use consistent tone and format
-- 8. Reference related objects (FKs, triggers)
-- 9. Document edge cases and limitations
-- 10. Add migration notes for breaking changes
