#!/bin/bash

# Scan System Core Library
# Reusable functions for all scan operations

# Set strict mode
set -euo pipefail

# Constants
SCAN_REGISTRY="expansion-packs/super-agentes/scan-system/registry.yaml"
SCAN_CONFIG="expansion-packs/super-agentes/scan-system/config.yaml"

# Function: Get next artifact ID for an agent
# Usage: get_next_artifact_id "design-system"
get_next_artifact_id() {
    local agent_name=$1

    # Check registry exists
    if [[ ! -f "$SCAN_REGISTRY" ]]; then
        echo "ERROR: Registry file not found at $SCAN_REGISTRY" >&2
        return 1
    fi

    # Get last ID for this agent
    local last_id=$(yq eval ".agents.${agent_name}.last_id // 0" "$SCAN_REGISTRY")

    # Increment and format with leading zeros
    local next_id=$(printf "%03d" $((10#$last_id + 1)))

    echo "$next_id"
}

# Function: Update registry with new artifact
# Usage: update_registry "design-system" "001" "artifact-001-dashboard.md"
update_registry() {
    local agent_name=$1
    local artifact_id=$2
    local artifact_path=$3

    # Create backup
    cp "$SCAN_REGISTRY" "${SCAN_REGISTRY}.bak"

    # Update last_id
    yq eval ".agents.${agent_name}.last_id = ${artifact_id#0}" -i "$SCAN_REGISTRY"

    # Increment total_scans
    yq eval ".agents.${agent_name}.total_scans += 1" -i "$SCAN_REGISTRY"

    # Add to artifacts array
    yq eval ".agents.${agent_name}.artifacts += [{\"id\": \"${artifact_id}\", \"path\": \"${artifact_path}\", \"created_at\": \"$(date -Iseconds)\"}]" -i "$SCAN_REGISTRY"

    # Update last_updated
    yq eval ".last_updated = \"$(date -Iseconds)\"" -i "$SCAN_REGISTRY"

    echo "Registry updated successfully"
}

# Function: Create metadata file
# Usage: create_metadata "design-system" "001" "artifact-analysis" "dashboard"
create_metadata() {
    local agent_name=$1
    local artifact_id=$2
    local scan_type=$3
    local artifact_name=$4

    local metadata_dir=$(yq eval ".agents.${agent_name}.metadata_dir" "$SCAN_CONFIG")
    local metadata_file="${metadata_dir}${artifact_id}.yaml"

    # Ensure directory exists
    mkdir -p "$metadata_dir"

    # Create metadata file
    cat > "$metadata_file" << METADATA
# Scan Artifact Metadata
# Auto-generated by scan system

artifact:
  id: "${artifact_id}"
  agent: "${agent_name}"
  scan_type: "${scan_type}"
  name: "${artifact_name}"
  created_at: "$(date -Iseconds)"
  created_by: "$(git config user.name 2>/dev/null || echo 'unknown')"
  git_commit: "$(git rev-parse HEAD 2>/dev/null || echo 'uncommitted')"

source:
  target: "TBD - set by scan task"
  size_bytes: 0

analysis:
  metrics:
    # Will be populated by scan task
    placeholder: 0

  extracted_data:
    # Will be populated by scan task
    placeholder: []

tags: []
status: "in_progress"
version: "1.0"
METADATA

    echo "$metadata_file"
}

# Function: Commit scan artifacts to git
# Usage: commit_scan_artifacts "design-system" "001" "artifact-analysis"
commit_scan_artifacts() {
    local agent_name=$1
    local artifact_id=$2
    local scan_type=$3

    # Check if git is available
    if ! command -v git &> /dev/null; then
        echo "WARNING: Git not available, skipping commit"
        return 0
    fi

    # Get output directory
    local output_dir=$(yq eval ".agents.${agent_name}.output_dir" "$SCAN_CONFIG")
    local metadata_dir=$(yq eval ".agents.${agent_name}.metadata_dir" "$SCAN_CONFIG")

    # Stage files
    git add "${output_dir}artifact-${artifact_id}-*.md" 2>/dev/null || true
    git add "${metadata_dir}${artifact_id}.yaml" 2>/dev/null || true
    git add "$SCAN_REGISTRY" 2>/dev/null || true

    # Create commit
    local commit_msg="docs(${agent_name}): add ${scan_type} artifact ${artifact_id}

Generated by scan system
Type: ${scan_type}
Agent: ${agent_name}"

    git commit -m "$commit_msg" 2>/dev/null || {
        echo "WARNING: Could not create git commit (files may already be committed)"
        return 0
    }

    echo "Changes committed to git"
}

# Function: Validate scan environment
# Usage: validate_scan_environment "design-system"
validate_scan_environment() {
    local agent_name=$1

    # Check agent is enabled
    local enabled=$(yq eval ".agents.${agent_name}.enabled // false" "$SCAN_CONFIG")
    if [[ "$enabled" != "true" ]]; then
        echo "ERROR: Agent ${agent_name} is not enabled for scanning" >&2
        return 1
    fi

    # Check output directory exists
    local output_dir=$(yq eval ".agents.${agent_name}.output_dir" "$SCAN_CONFIG")
    if [[ ! -d "$output_dir" ]]; then
        echo "Creating output directory: $output_dir"
        mkdir -p "$output_dir"
    fi

    # Check yq is available
    if ! command -v yq &> /dev/null; then
        echo "ERROR: yq is required but not installed" >&2
        echo "Install with: brew install yq (macOS) or download from https://github.com/mikefarah/yq" >&2
        return 1
    fi

    echo "Environment validated for ${agent_name}"
    return 0
}

# Export functions for use in other scripts
export -f get_next_artifact_id
export -f update_registry
export -f create_metadata
export -f commit_scan_artifacts
export -f validate_scan_environment

echo "Scan core library loaded successfully"
