/**
 * Tailwind CSS Configuration - Mente Lendária Design System
 * Version: 1.0.0
 * Generated by: Brad Frost (Design System Architect)
 * Generated at: 2025-10-28
 *
 * Usage: Copy this config to your tailwind.config.js
 * Or import: const tokens = require('./tailwind.config.js')
 */

module.exports = {
  theme: {
    extend: {
      // ========================================
      // COLORS
      // ========================================
      colors: {
        // Background colors
        bg: {
          primary: '#191919',
          secondary: '#262625',
          tertiary: '#2d2d2b',
          elevated: '#40403E',
        },

        // Accent colors
        accent: {
          primary: '#CC785C',
          secondary: '#BF4D43',
          tertiary: '#D4A27F',
          light: '#EBD8BC',
        },

        // Text colors
        text: {
          primary: '#F0F0E8',
          secondary: '#919180',
          inverted: '#FFFFFF',
        },

        // Status colors
        status: {
          success: '#48bb78',
          warning: '#ecc94b',
          error: '#f56565',
          info: '#3498db',
        },

        // Agent colors (domain-specific)
        agent: {
          analyst: '#2d6a4f',
          pm: '#ca6702',
          ux: '#1e6091',
          architect: '#5a189a',
          po: '#c77700',
          dev: '#0077b6',
          qa: '#9b870c',
        },
      },

      // ========================================
      // GRADIENTS (via backgroundImage)
      // ========================================
      backgroundImage: {
        'gradient-blue': 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
        'gradient-green': 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)',
        'gradient-pink-yellow': 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
        'gradient-teal-purple': 'linear-gradient(135deg, #30cfd0 0%, #330867 100%)',
        'gradient-phase-1': 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
        'gradient-phase-2': 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)',
        'gradient-phase-3': 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
        'gradient-phase-4': 'linear-gradient(135deg, #30cfd0 0%, #330867 100%)',
      },

      // ========================================
      // SPACING
      // ========================================
      spacing: {
        xs: '0.25rem',  // 4px
        sm: '0.5rem',   // 8px
        md: '0.75rem',  // 12px
        lg: '1rem',     // 16px
        xl: '1.5rem',   // 24px
        '2xl': '2rem',  // 32px
        '3xl': '3rem',  // 48px
      },

      // ========================================
      // BORDER RADIUS
      // ========================================
      borderRadius: {
        sm: '0.25rem',  // 4px
        DEFAULT: '0.5rem',  // 8px (md)
        md: '0.5rem',   // 8px
        lg: '0.75rem',  // 12px
        full: '9999px', // Full radius
      },

      // ========================================
      // TYPOGRAPHY
      // ========================================

      // Font families
      fontFamily: {
        sans: ['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Helvetica Neue', 'Arial', 'sans-serif'],
        serif: ['Georgia', 'serif'],
        mono: ['SF Mono', 'Monaco', 'Cascadia Code', 'monospace'],
      },

      // Font sizes
      fontSize: {
        tiny: '0.7rem',       // 11.2px
        small: '0.875rem',    // 14px
        base: '1rem',         // 16px
        large: '1.25rem',     // 20px
        heading: '1.25rem',   // 20px - h4
        subsection: '1.5rem', // 24px - h3
        section: '2rem',      // 32px - h2
        hero: '3rem',         // 48px - h1
      },

      // Font weights
      fontWeight: {
        light: 300,
        normal: 400,
        semibold: 600,
        bold: 700,
      },

      // Line heights
      lineHeight: {
        tight: '1.25',
        normal: '1.5',
        relaxed: '1.625',
        loose: '1.8',
      },

      // ========================================
      // BREAKPOINTS (screens in Tailwind)
      // ========================================
      screens: {
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1536px',
      },
    },
  },
  plugins: [],
}

// ========================================
// USAGE EXAMPLES
// ========================================
//
// Background colors:
// <div className="bg-bg-secondary">...</div>
//
// Text colors:
// <p className="text-text-primary">...</p>
//
// Status colors:
// <span className="text-status-success">✓</span>
//
// Gradients:
// <div className="bg-gradient-blue">...</div>
//
// Spacing:
// <div className="p-xl m-2xl">...</div>
//
// Border radius:
// <button className="rounded-lg">...</button>
//
// Typography:
// <h1 className="font-sans text-hero font-bold leading-tight">...</h1>
//
// Responsive:
// <div className="p-md md:p-xl lg:p-2xl">...</div>
//
// Agent colors:
// <div className="bg-agent-dev">Dev Agent</div>
